import { Request, Response } from "express";
import { Source } from "@/app/models/source.models";
import { LLM } from "@/app/llm/llm";
import { loadDocument } from "../loader/loaders";
import { DocRepository } from "../repository/DocRepository";
import { downloadFromStorage } from "@/services/storage/download.service";
import { uploadToStorage } from "@/services/storage/upload.service";
import path from "path";
import crypto from "crypto";
import fs from "fs";
import { cwd } from "process";
import { generatePPTStructure } from "@/pipelines/ppt";
import { Document } from "@langchain/core/documents";
import PptxGenJS from "pptxgenjs";

export async function generatePPTController(req: Request, res: Response) {
    try {
        const { noteId, docIds } = req.body;
        const userId = (req as any).userId || (req.user as any)?._id?.toString() || (req.user as any)?.authData?._id?.toString();

        if (!userId || !noteId || !docIds || docIds.length === 0) {
            return res.status(400).json({ success: false, message: "Missing required fields." });
        }

        const llm = LLM.getInstance();
        const docRepo = DocRepository.getInstance();

        const splitDocs = [];
        
        for (const docId of docIds) {
            const doc = await docRepo.getSingleDoc2({_id: docId, userId, noteId});
            if (!doc) continue;

            const storageKey = doc?.fileName as string;
            
            try {
                if (storageKey && storageKey.trim() !== "") {
                    const tempPath = path.join(cwd(), "tmp", crypto.randomUUID() + "-" + path.basename(storageKey));
                    if (!fs.existsSync(path.join(cwd(), "tmp"))) fs.mkdirSync(path.join(cwd(), "tmp"));
                    
                    await downloadFromStorage(storageKey, tempPath);
                    let splittingDoc;
            try {
                splittingDoc = await loadDocument(tempPath);
            } finally {
                if (fs.existsSync(tempPath)) fs.unlinkSync(tempPath);
            }

                    splitDocs.push(...splittingDoc);
                } else {
                    splitDocs.push(new Document({ pageContent: doc.summary || doc.title }));
                }
            } catch (err) {
                if (doc.summary || doc.title) {
                    splitDocs.push(new Document({ pageContent: doc.summary || doc.title }));
                }
            }
        }

        if (splitDocs.length === 0) {
            return res.status(400).json({ success: false, message: "No valid documents found." });
        }

        const pptData = await generatePPTStructure(llm, splitDocs);
        
        // Build the actual PPTX file
        const pres = new PptxGenJS();
        
        // Title Slide
        const titleSlide = pres.addSlide();
        titleSlide.addText(pptData.title, { x: 1, y: 2, w: '80%', fontSize: 36, bold: true, align: 'center', color: '363636' });
        titleSlide.addText(pptData.subtitle || 'Generated by AI', { x: 1, y: 3.5, w: '80%', fontSize: 24, align: 'center', color: '666666' });
        
        // Content Slides
        for (const slideData of pptData.slides) {
            const slide = pres.addSlide();
            slide.addText(slideData.title, { x: 0.5, y: 0.5, w: '90%', h: 1, fontSize: 32, bold: true, color: '363636' });
            
            const bulletText = slideData.bullets.map(b => ({ text: b, options: { bullet: true, breakLine: true } }));
            slide.addText(bulletText, { x: 0.5, y: 1.8, w: '90%', h: 3.5, fontSize: 22, color: '363636', valign: 'top' });
            
            if (slideData.notes) {
                slide.addNotes(slideData.notes);
            }
        }

        // Generate Buffer
        const buffer = await pres.write({ outputType: 'nodebuffer' }) as Buffer;
        
        // Upload to storage
        const storageKey = await uploadToStorage(buffer, 'presentation.pptx', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'ppts');

        // Save as Source so it appears in the generated list
        const source = await Source.create({
            title: pptData.title || `Presentation - ${new Date().toLocaleDateString()}`,
            displayName: 'Presentation.pptx',
            total_source: docIds.length,
            content: storageKey,
            source_type: 'ppt',
            noteId,
            userId,
            status: 'indexed'
        });

        return res.status(200).json({ success: true, message: 'Presentation generated successfully', source });
    } catch (error: any) {
        console.error("Error generating PPT", error);
        return res.status(500).json({ success: false, message: error.message || "Failed to generate presentation" });
    }
}
