export const T = {
  font: "'Instrument Serif', 'Playfair Display', Georgia, serif",
  fontSans: "'DM Sans', 'Outfit', system-ui, sans-serif",
  fontMono: "'DM Mono', monospace",
  bg: "var(--bg-base)",
  bgSurface: "var(--bg-surface)",
  bgCard: "var(--bg-card)",
  bgCardHover: "var(--bg-card-hover)",
  border: "var(--border-default)",
  borderHover: "var(--border-hover)",
  borderAccent: "var(--border-accent)",
  primary: "var(--primary-brand)",
  primaryLight: "var(--primary-light)",
  primaryGlow: "var(--primary-glow)",
  primaryMid: "var(--primary-mid)",
  text1: "var(--text-1)",
  text2: "var(--text-2)",
  text3: "var(--text-3)",
  accent: "#c4b5fd",
  green: "#4ade80",
  radius: "18px",
  radiusSm: "10px",
  shadow: "0 32px 64px rgba(0,0,0,0.5)",
  shadowCard: "0 8px 32px rgba(0,0,0,0.3)",
};
